// Standardized error response interface and error codes
import { ApiProperty } from '@nestjs/swagger';

export enum ErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT = 'INVALID_FORMAT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_MFA_REQUIRED = 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID = 'AUTH_MFA_INVALID',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_PASSWORD_EXPIRED = 'AUTH_PASSWORD_EXPIRED',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_EMAIL_NOT_VERIFIED = 'USER_EMAIL_NOT_VERIFIED',
  USER_INVALID_EMAIL = 'USER_INVALID_EMAIL',
  USER_INVALID_PASSWORD = 'USER_INVALID_PASSWORD',
  USER_PASSWORD_MISMATCH = 'USER_PASSWORD_MISMATCH',
  USER_PROFILE_INCOMPLETE = 'USER_PROFILE_INCOMPLETE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_ARCHIVED = 'RESOURCE_ARCHIVED',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_NOT_PUBLISHED = 'COURSE_NOT_PUBLISHED',
  COURSE_ENROLLMENT_CLOSED = 'COURSE_ENROLLMENT_CLOSED',
  COURSE_ALREADY_ENROLLED = 'COURSE_ALREADY_ENROLLED',
  COURSE_PREREQUISITE_NOT_MET = 'COURSE_PREREQUISITE_NOT_MET',
  COURSE_CAPACITY_REACHED = 'COURSE_CAPACITY_REACHED',
  COURSE_INVALID_MODULE = 'COURSE_INVALID_MODULE',
  COURSE_INVALID_LESSON = 'COURSE_INVALID_LESSON',
  ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_DEADLINE_PASSED = 'ASSIGNMENT_DEADLINE_PASSED',
  ASSIGNMENT_NOT_SUBMITTED = 'ASSIGNMENT_NOT_SUBMITTED',
  ASSIGNMENT_ALREADY_GRADED = 'ASSIGNMENT_ALREADY_GRADED',
  ASSIGNMENT_SUBMISSION_INVALID = 'ASSIGNMENT_SUBMISSION_INVALID',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  PAYMENT_AMOUNT_INVALID = 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_CURRENCY_INVALID = 'PAYMENT_CURRENCY_INVALID',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  REFUND_NOT_POSSIBLE = 'REFUND_NOT_POSSIBLE',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_INVALID = 'FILE_TYPE_INVALID',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_VIRUS_DETECTED = 'FILE_VIRUS_DETECTED',
  BLOCKCHAIN_TRANSACTION_FAILED = 'BLOCKCHAIN_TRANSACTION_FAILED',
  BLOCKCHAIN_INSUFFICIENT_FUNDS = 'BLOCKCHAIN_INSUFFICIENT_FUNDS',
  BLOCKCHAIN_INVALID_WALLET = 'BLOCKCHAIN_INVALID_WALLET',
  BLOCKCHAIN_NETWORK_ERROR = 'BLOCKCHAIN_NETWORK_ERROR',
  BLOCKCHAIN_SIGNATURE_INVALID = 'BLOCKCHAIN_SIGNATURE_INVALID',
  CREDENTIAL_VERIFICATION_FAILED = 'CREDENTIAL_VERIFICATION_FAILED',
  FORUM_POST_NOT_FOUND = 'FORUM_POST_NOT_FOUND',
  FORUM_THREAD_LOCKED = 'FORUM_THREAD_LOCKED',
  FORUM_ACCESS_DENIED = 'FORUM_ACCESS_DENIED',
  FORUM_REPLY_NOT_ALLOWED = 'FORUM_REPLY_NOT_ALLOWED',
  INTEGRATION_NOT_CONFIGURED = 'INTEGRATION_NOT_CONFIGURED',
  INTEGRATION_AUTH_FAILED = 'INTEGRATION_AUTH_FAILED',
  INTEGRATION_RATE_LIMITED = 'INTEGRATION_RATE_LIMITED',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  INTEGRATION_TIMEOUT = 'INTEGRATION_TIMEOUT',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',
  DATABASE_TIMEOUT = 'DATABASE_TIMEOUT',
  DATABASE_CONSTRAINT_VIOLATION = 'DATABASE_CONSTRAINT_VIOLATION',
  CACHE_ERROR = 'CACHE_ERROR',
  CACHE_MISS = 'CACHE_MISS',
}

export enum ErrorSeverity { LOW = 'low', MEDIUM = 'medium', HIGH = 'high', CRITICAL = 'critical' }
export enum ErrorCategory { VALIDATION = 'validation', AUTHENTICATION = 'authentication', AUTHORIZATION = 'authorization', BUSINESS_LOGIC = 'business_logic', INTEGRATION = 'integration', SYSTEM = 'system', EXTERNAL = 'external' }

export class ErrorDetail {
  @ApiProperty() field?: string;
  @ApiProperty() code: string;
  @ApiProperty() message: string;
  suggestion?: string;
  value?: unknown;
}

export class StandardizedErrorResponse {
  @ApiProperty() success: false;
  @ApiProperty() errorCode: ErrorCode;
  @ApiProperty() message: string;
  detail?: string;
  statusCode: number;
  severity?: ErrorSeverity;
  category?: ErrorCategory;
  errors?: ErrorDetail[];
  requestId: string;
  timestamp: string;
  path: string;
  method: string;
  documentationUrl?: string;
  stack?: string;
  debug?: Record<string, unknown>;
}

export interface ErrorResponse { statusCode: number; message: string; error?: string; timestamp: string; path: string; requestId?: string; details?: unknown; }
export interface ErrorResponseOptions { errorCode: ErrorCode; message?: string; detail?: string; statusCode?: number; severity?: ErrorSeverity; category?: ErrorCategory; errors?: ErrorDetail[]; cause?: Error; documentationUrl?: string; debug?: Record<string, unknown>; }

export const ERROR_STATUS_MAP: Partial<Record<ErrorCode, number>> = {
  [ErrorCode.VALIDATION_ERROR]: 400, [ErrorCode.INVALID_INPUT]: 400, [ErrorCode.MISSING_REQUIRED_FIELD]: 400,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401, [ErrorCode.AUTH_TOKEN_EXPIRED]: 401, [ErrorCode.AUTH_TOKEN_INVALID]: 401, [ErrorCode.AUTH_TOKEN_MISSING]: 401, [ErrorCode.AUTH_UNAUTHORIZED]: 401,
  [ErrorCode.AUTH_FORBIDDEN]: 403, [ErrorCode.AUTH_ACCOUNT_DISABLED]: 403, [ErrorCode.AUTH_ACCOUNT_LOCKED]: 403,
  [ErrorCode.USER_NOT_FOUND]: 404, [ErrorCode.RESOURCE_NOT_FOUND]: 404, [ErrorCode.COURSE_NOT_FOUND]: 404, [ErrorCode.ASSIGNMENT_NOT_FOUND]: 404, [ErrorCode.FILE_NOT_FOUND]: 404,
  [ErrorCode.USER_ALREADY_EXISTS]: 409, [ErrorCode.RESOURCE_CONFLICT]: 409, [ErrorCode.COURSE_ALREADY_ENROLLED]: 409,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429, [ErrorCode.UNKNOWN_ERROR]: 500, [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.DATABASE_CONNECTION_ERROR]: 500, [ErrorCode.INTEGRATION_ERROR]: 502, [ErrorCode.SERVICE_UNAVAILABLE]: 503, [ErrorCode.FILE_TOO_LARGE]: 413, [ErrorCode.PAYMENT_FAILED]: 402,
};

export const ERROR_SEVERITY_MAP: Partial<Record<ErrorCode, ErrorSeverity>> = {
  [ErrorCode.UNKNOWN_ERROR]: ErrorSeverity.HIGH, [ErrorCode.INTERNAL_SERVER_ERROR]: ErrorSeverity.CRITICAL,
  [ErrorCode.DATABASE_CONNECTION_ERROR]: ErrorSeverity.CRITICAL, [ErrorCode.RATE_LIMIT_EXCEEDED]: ErrorSeverity.LOW,
  [ErrorCode.VALIDATION_ERROR]: ErrorSeverity.LOW, [ErrorCode.AUTH_TOKEN_EXPIRED]: ErrorSeverity.LOW,
  [ErrorCode.AUTH_UNAUTHORIZED]: ErrorSeverity.MEDIUM, [ErrorCode.AUTH_FORBIDDEN]: ErrorSeverity.MEDIUM,
};

export const ERROR_CATEGORY_MAP: Partial<Record<ErrorCode, ErrorCategory>> = {
  [ErrorCode.VALIDATION_ERROR]: ErrorCategory.VALIDATION, [ErrorCode.INVALID_INPUT]: ErrorCategory.VALIDATION,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: ErrorCategory.AUTHENTICATION, [ErrorCode.AUTH_TOKEN_EXPIRED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_UNAUTHORIZED]: ErrorCategory.AUTHENTICATION, [ErrorCode.AUTH_FORBIDDEN]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.RESOURCE_NOT_FOUND]: ErrorCategory.BUSINESS_LOGIC, [ErrorCode.INTEGRATION_ERROR]: ErrorCategory.INTEGRATION,
  [ErrorCode.INTERNAL_SERVER_ERROR]: ErrorCategory.SYSTEM, [ErrorCode.PAYMENT_FAILED]: ErrorCategory.EXTERNAL,
};
